/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

type ErrorWithCode = Error & { code: number }
type MaybeErrorWithCode = ErrorWithCode | null | undefined

const createErrorFromCodeLookup: Map<number, () => ErrorWithCode> = new Map()
const createErrorFromNameLookup: Map<string, () => ErrorWithCode> = new Map()

/**
 * BlockNotEnum: 'The type of block is not enum, block definitions must only be created for enum'
 *
 * @category Errors
 * @category generated
 */
export class BlockNotEnumError extends Error {
  readonly code: number = 0x1770
  readonly name: string = 'BlockNotEnum'
  constructor() {
    super(
      'The type of block is not enum, block definitions must only be created for enum'
    )
    if (typeof Error.captureStackTrace === 'function') {
      Error.captureStackTrace(this, BlockNotEnumError)
    }
  }
}

createErrorFromCodeLookup.set(0x1770, () => new BlockNotEnumError())
createErrorFromNameLookup.set('BlockNotEnum', () => new BlockNotEnumError())

/**
 * BlockNotNumber: 'The type of block is not number, block definitions must only be created for number'
 *
 * @category Errors
 * @category generated
 */
export class BlockNotNumberError extends Error {
  readonly code: number = 0x1771
  readonly name: string = 'BlockNotNumber'
  constructor() {
    super(
      'The type of block is not number, block definitions must only be created for number'
    )
    if (typeof Error.captureStackTrace === 'function') {
      Error.captureStackTrace(this, BlockNotNumberError)
    }
  }
}

createErrorFromCodeLookup.set(0x1771, () => new BlockNotNumberError())
createErrorFromNameLookup.set('BlockNotNumber', () => new BlockNotNumberError())

/**
 * BlockNotBoolean: 'The type of block is not boolean, block definitions must only be created for boolean'
 *
 * @category Errors
 * @category generated
 */
export class BlockNotBooleanError extends Error {
  readonly code: number = 0x1772
  readonly name: string = 'BlockNotBoolean'
  constructor() {
    super(
      'The type of block is not boolean, block definitions must only be created for boolean'
    )
    if (typeof Error.captureStackTrace === 'function') {
      Error.captureStackTrace(this, BlockNotBooleanError)
    }
  }
}

createErrorFromCodeLookup.set(0x1772, () => new BlockNotBooleanError())
createErrorFromNameLookup.set(
  'BlockNotBoolean',
  () => new BlockNotBooleanError()
)

/**
 * RequiredBlockImage: 'The particular block requires an image in definition'
 *
 * @category Errors
 * @category generated
 */
export class RequiredBlockImageError extends Error {
  readonly code: number = 0x1773
  readonly name: string = 'RequiredBlockImage'
  constructor() {
    super('The particular block requires an image in definition')
    if (typeof Error.captureStackTrace === 'function') {
      Error.captureStackTrace(this, RequiredBlockImageError)
    }
  }
}

createErrorFromCodeLookup.set(0x1773, () => new RequiredBlockImageError())
createErrorFromNameLookup.set(
  'RequiredBlockImage',
  () => new RequiredBlockImageError()
)

/**
 * InvalidBlockType: 'The block has an invalid type'
 *
 * @category Errors
 * @category generated
 */
export class InvalidBlockTypeError extends Error {
  readonly code: number = 0x1774
  readonly name: string = 'InvalidBlockType'
  constructor() {
    super('The block has an invalid type')
    if (typeof Error.captureStackTrace === 'function') {
      Error.captureStackTrace(this, InvalidBlockTypeError)
    }
  }
}

createErrorFromCodeLookup.set(0x1774, () => new InvalidBlockTypeError())
createErrorFromNameLookup.set(
  'InvalidBlockType',
  () => new InvalidBlockTypeError()
)

/**
 * InvalidBlockDefinition: 'The block defintion is invalid'
 *
 * @category Errors
 * @category generated
 */
export class InvalidBlockDefinitionError extends Error {
  readonly code: number = 0x1775
  readonly name: string = 'InvalidBlockDefinition'
  constructor() {
    super('The block defintion is invalid')
    if (typeof Error.captureStackTrace === 'function') {
      Error.captureStackTrace(this, InvalidBlockDefinitionError)
    }
  }
}

createErrorFromCodeLookup.set(0x1775, () => new InvalidBlockDefinitionError())
createErrorFromNameLookup.set(
  'InvalidBlockDefinition',
  () => new InvalidBlockDefinitionError()
)

/**
 * InvalidMetadata: 'The metadata provided for the mint is not valid'
 *
 * @category Errors
 * @category generated
 */
export class InvalidMetadataError extends Error {
  readonly code: number = 0x1776
  readonly name: string = 'InvalidMetadata'
  constructor() {
    super('The metadata provided for the mint is not valid')
    if (typeof Error.captureStackTrace === 'function') {
      Error.captureStackTrace(this, InvalidMetadataError)
    }
  }
}

createErrorFromCodeLookup.set(0x1776, () => new InvalidMetadataError())
createErrorFromNameLookup.set(
  'InvalidMetadata',
  () => new InvalidMetadataError()
)

/**
 * InvalidTokenForBlockDefinition: 'The token is not valid for this block definition'
 *
 * @category Errors
 * @category generated
 */
export class InvalidTokenForBlockDefinitionError extends Error {
  readonly code: number = 0x1777
  readonly name: string = 'InvalidTokenForBlockDefinition'
  constructor() {
    super('The token is not valid for this block definition')
    if (typeof Error.captureStackTrace === 'function') {
      Error.captureStackTrace(this, InvalidTokenForBlockDefinitionError)
    }
  }
}

createErrorFromCodeLookup.set(
  0x1777,
  () => new InvalidTokenForBlockDefinitionError()
)
createErrorFromNameLookup.set(
  'InvalidTokenForBlockDefinition',
  () => new InvalidTokenForBlockDefinitionError()
)

/**
 * NFTAlreadyMinted: 'The NFT is already minted'
 *
 * @category Errors
 * @category generated
 */
export class NFTAlreadyMintedError extends Error {
  readonly code: number = 0x1778
  readonly name: string = 'NFTAlreadyMinted'
  constructor() {
    super('The NFT is already minted')
    if (typeof Error.captureStackTrace === 'function') {
      Error.captureStackTrace(this, NFTAlreadyMintedError)
    }
  }
}

createErrorFromCodeLookup.set(0x1778, () => new NFTAlreadyMintedError())
createErrorFromNameLookup.set(
  'NFTAlreadyMinted',
  () => new NFTAlreadyMintedError()
)

/**
 * Attempts to resolve a custom program error from the provided error code.
 * @category Errors
 * @category generated
 */
export function errorFromCode(code: number): MaybeErrorWithCode {
  const createError = createErrorFromCodeLookup.get(code)
  return createError != null ? createError() : null
}

/**
 * Attempts to resolve a custom program error from the provided error name, i.e. 'Unauthorized'.
 * @category Errors
 * @category generated
 */
export function errorFromName(name: string): MaybeErrorWithCode {
  const createError = createErrorFromNameLookup.get(name)
  return createError != null ? createError() : null
}
