/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type CreateBlockDefinitionNumberArgs = {
  min: beet.bignum
  max: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const createBlockDefinitionNumberArgsBeet =
  new beet.BeetArgsStruct<CreateBlockDefinitionNumberArgs>(
    [
      ['min', beet.u64],
      ['max', beet.u64],
    ],
    'CreateBlockDefinitionNumberArgs'
  )
