[features]
seeds = false
skip-lint = false
[programs.devnet]
anchor_template = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[provider]
cluster = "devnet"
wallet = "authority.json"

[scripts]
test = "yarn test"
