[workspace]
members = [
  "programs/hpl-asset-manager",
  "programs/hpl-asset-assembler",
  "programs/hpl-currency-manager",
  "programs/hpl-payment-manager",
  "programs/hpl-character-manager",
  "programs/hpl-resource-manager",
]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
