[package]
name = "hpl-asset-assembler"
description = "Honeycomb protocol library assembler program"
author = ['Sultan Nadeem <sultanndilaram@gmail.com>']
version = "0.0.43"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "lib"]
name = "hpl_asset_assembler"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.26.0"
anchor-spl = "0.26.0"
getrandom = { version = "0.2.9", features = ["custom"] }
solana-program = "=1.14.17"
winnow = "=0.4.1"
toml_datetime = "=0.6.1"
hpl-utils = "0.1.4"
hpl-hive-control = { version="0.1.23", features = ["cpi"] }
mpl-token-metadata = { version="1.9.0", features = [ "no-entrypoint" ] }
spl-account-compression = { version="0.1.8", features=["cpi"] }
