/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link BlockDefinitionBoolean}
 * @category Accounts
 * @category generated
 */
export type BlockDefinitionBooleanArgs = {
  bump: number
  block: web3.PublicKey
  value: boolean
}

export const blockDefinitionBooleanDiscriminator = [
  188, 13, 157, 245, 205, 83, 200, 45,
]
/**
 * Holds the data for the {@link BlockDefinitionBoolean} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class BlockDefinitionBoolean implements BlockDefinitionBooleanArgs {
  private constructor(
    readonly bump: number,
    readonly block: web3.PublicKey,
    readonly value: boolean
  ) {}

  /**
   * Creates a {@link BlockDefinitionBoolean} instance from the provided args.
   */
  static fromArgs(args: BlockDefinitionBooleanArgs) {
    return new BlockDefinitionBoolean(args.bump, args.block, args.value)
  }

  /**
   * Deserializes the {@link BlockDefinitionBoolean} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [BlockDefinitionBoolean, number] {
    return BlockDefinitionBoolean.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link BlockDefinitionBoolean} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<BlockDefinitionBoolean> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(
        `Unable to find BlockDefinitionBoolean account at ${address}`
      )
    }
    return BlockDefinitionBoolean.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'AXX2agYcoDwGFsgEWvSitqfGH4ooKXUqK5P7Ch9raDJT'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(
      programId,
      blockDefinitionBooleanBeet
    )
  }

  /**
   * Deserializes the {@link BlockDefinitionBoolean} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(
    buf: Buffer,
    offset = 0
  ): [BlockDefinitionBoolean, number] {
    return blockDefinitionBooleanBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link BlockDefinitionBoolean} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return blockDefinitionBooleanBeet.serialize({
      accountDiscriminator: blockDefinitionBooleanDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link BlockDefinitionBoolean}
   */
  static get byteSize() {
    return blockDefinitionBooleanBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link BlockDefinitionBoolean} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      BlockDefinitionBoolean.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link BlockDefinitionBoolean} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === BlockDefinitionBoolean.byteSize
  }

  /**
   * Returns a readable version of {@link BlockDefinitionBoolean} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      block: this.block.toBase58(),
      value: this.value,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const blockDefinitionBooleanBeet = new beet.BeetStruct<
  BlockDefinitionBoolean,
  BlockDefinitionBooleanArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
    ['block', beetSolana.publicKey],
    ['value', beet.bool],
  ],
  BlockDefinitionBoolean.fromArgs,
  'BlockDefinitionBoolean'
)
