/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link BlockDefinitionNumber}
 * @category Accounts
 * @category generated
 */
export type BlockDefinitionNumberArgs = {
  bump: number
  block: web3.PublicKey
  min: beet.bignum
  max: beet.bignum
}

export const blockDefinitionNumberDiscriminator = [
  177, 133, 211, 164, 79, 155, 99, 23,
]
/**
 * Holds the data for the {@link BlockDefinitionNumber} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class BlockDefinitionNumber implements BlockDefinitionNumberArgs {
  private constructor(
    readonly bump: number,
    readonly block: web3.PublicKey,
    readonly min: beet.bignum,
    readonly max: beet.bignum
  ) {}

  /**
   * Creates a {@link BlockDefinitionNumber} instance from the provided args.
   */
  static fromArgs(args: BlockDefinitionNumberArgs) {
    return new BlockDefinitionNumber(args.bump, args.block, args.min, args.max)
  }

  /**
   * Deserializes the {@link BlockDefinitionNumber} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [BlockDefinitionNumber, number] {
    return BlockDefinitionNumber.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link BlockDefinitionNumber} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<BlockDefinitionNumber> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(
        `Unable to find BlockDefinitionNumber account at ${address}`
      )
    }
    return BlockDefinitionNumber.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'AXX2agYcoDwGFsgEWvSitqfGH4ooKXUqK5P7Ch9raDJT'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(
      programId,
      blockDefinitionNumberBeet
    )
  }

  /**
   * Deserializes the {@link BlockDefinitionNumber} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [BlockDefinitionNumber, number] {
    return blockDefinitionNumberBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link BlockDefinitionNumber} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return blockDefinitionNumberBeet.serialize({
      accountDiscriminator: blockDefinitionNumberDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link BlockDefinitionNumber}
   */
  static get byteSize() {
    return blockDefinitionNumberBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link BlockDefinitionNumber} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      BlockDefinitionNumber.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link BlockDefinitionNumber} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === BlockDefinitionNumber.byteSize
  }

  /**
   * Returns a readable version of {@link BlockDefinitionNumber} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      block: this.block.toBase58(),
      min: (() => {
        const x = <{ toNumber: () => number }>this.min
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      max: (() => {
        const x = <{ toNumber: () => number }>this.max
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const blockDefinitionNumberBeet = new beet.BeetStruct<
  BlockDefinitionNumber,
  BlockDefinitionNumberArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
    ['block', beetSolana.publicKey],
    ['min', beet.u64],
    ['max', beet.u64],
  ],
  BlockDefinitionNumber.fromArgs,
  'BlockDefinitionNumber'
)
