/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link NFTAttribute}
 * @category Accounts
 * @category generated
 */
export type NFTAttributeArgs = {
  bump: number
  nft: web3.PublicKey
  block: web3.PublicKey
  blockDefinition: web3.PublicKey
  attributeName: string
  attributeValue: string
}

export const nFTAttributeDiscriminator = [161, 3, 226, 65, 113, 87, 24, 132]
/**
 * Holds the data for the {@link NFTAttribute} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class NFTAttribute implements NFTAttributeArgs {
  private constructor(
    readonly bump: number,
    readonly nft: web3.PublicKey,
    readonly block: web3.PublicKey,
    readonly blockDefinition: web3.PublicKey,
    readonly attributeName: string,
    readonly attributeValue: string
  ) {}

  /**
   * Creates a {@link NFTAttribute} instance from the provided args.
   */
  static fromArgs(args: NFTAttributeArgs) {
    return new NFTAttribute(
      args.bump,
      args.nft,
      args.block,
      args.blockDefinition,
      args.attributeName,
      args.attributeValue
    )
  }

  /**
   * Deserializes the {@link NFTAttribute} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [NFTAttribute, number] {
    return NFTAttribute.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link NFTAttribute} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<NFTAttribute> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find NFTAttribute account at ${address}`)
    }
    return NFTAttribute.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'AXX2agYcoDwGFsgEWvSitqfGH4ooKXUqK5P7Ch9raDJT'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, nFTAttributeBeet)
  }

  /**
   * Deserializes the {@link NFTAttribute} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [NFTAttribute, number] {
    return nFTAttributeBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link NFTAttribute} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return nFTAttributeBeet.serialize({
      accountDiscriminator: nFTAttributeDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link NFTAttribute} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: NFTAttributeArgs) {
    const instance = NFTAttribute.fromArgs(args)
    return nFTAttributeBeet.toFixedFromValue({
      accountDiscriminator: nFTAttributeDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link NFTAttribute} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: NFTAttributeArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      NFTAttribute.byteSize(args),
      commitment
    )
  }

  /**
   * Returns a readable version of {@link NFTAttribute} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      nft: this.nft.toBase58(),
      block: this.block.toBase58(),
      blockDefinition: this.blockDefinition.toBase58(),
      attributeName: this.attributeName,
      attributeValue: this.attributeValue,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const nFTAttributeBeet = new beet.FixableBeetStruct<
  NFTAttribute,
  NFTAttributeArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
    ['nft', beetSolana.publicKey],
    ['block', beetSolana.publicKey],
    ['blockDefinition', beetSolana.publicKey],
    ['attributeName', beet.utf8String],
    ['attributeValue', beet.utf8String],
  ],
  NFTAttribute.fromArgs,
  'NFTAttribute'
)
