/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  CreateBlockDefinitionBooleanArgs,
  createBlockDefinitionBooleanArgsBeet,
} from '../types/CreateBlockDefinitionBooleanArgs'

/**
 * @category Instructions
 * @category CreateBlockDefinitionBoolean
 * @category generated
 */
export type CreateBlockDefinitionBooleanInstructionArgs = {
  args: CreateBlockDefinitionBooleanArgs
}
/**
 * @category Instructions
 * @category CreateBlockDefinitionBoolean
 * @category generated
 */
export const createBlockDefinitionBooleanStruct = new beet.BeetArgsStruct<
  CreateBlockDefinitionBooleanInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['args', createBlockDefinitionBooleanArgsBeet],
  ],
  'CreateBlockDefinitionBooleanInstructionArgs'
)
/**
 * Accounts required by the _createBlockDefinitionBoolean_ instruction
 *
 * @property [] assembler
 * @property [] block
 * @property [_writable_] blockDefinition
 * @property [**signer**] authority
 * @property [_writable_, **signer**] payer
 * @category Instructions
 * @category CreateBlockDefinitionBoolean
 * @category generated
 */
export type CreateBlockDefinitionBooleanInstructionAccounts = {
  assembler: web3.PublicKey
  block: web3.PublicKey
  blockDefinition: web3.PublicKey
  authority: web3.PublicKey
  payer: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createBlockDefinitionBooleanInstructionDiscriminator = [
  23, 239, 25, 75, 162, 212, 50, 200,
]

/**
 * Creates a _CreateBlockDefinitionBoolean_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateBlockDefinitionBoolean
 * @category generated
 */
export function createCreateBlockDefinitionBooleanInstruction(
  accounts: CreateBlockDefinitionBooleanInstructionAccounts,
  args: CreateBlockDefinitionBooleanInstructionArgs,
  programId = new web3.PublicKey('AXX2agYcoDwGFsgEWvSitqfGH4ooKXUqK5P7Ch9raDJT')
) {
  const [data] = createBlockDefinitionBooleanStruct.serialize({
    instructionDiscriminator:
      createBlockDefinitionBooleanInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.assembler,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.block,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.blockDefinition,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.authority,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
