/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  CreateBlockDefinitionEnumArgs,
  createBlockDefinitionEnumArgsBeet,
} from '../types/CreateBlockDefinitionEnumArgs'

/**
 * @category Instructions
 * @category CreateBlockDefinitionEnum
 * @category generated
 */
export type CreateBlockDefinitionEnumInstructionArgs = {
  args: CreateBlockDefinitionEnumArgs
}
/**
 * @category Instructions
 * @category CreateBlockDefinitionEnum
 * @category generated
 */
export const createBlockDefinitionEnumStruct = new beet.FixableBeetArgsStruct<
  CreateBlockDefinitionEnumInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['args', createBlockDefinitionEnumArgsBeet],
  ],
  'CreateBlockDefinitionEnumInstructionArgs'
)
/**
 * Accounts required by the _createBlockDefinitionEnum_ instruction
 *
 * @property [] assembler
 * @property [] block
 * @property [_writable_] blockDefinition
 * @property [_writable_] blockDefinitionMint
 * @property [**signer**] authority
 * @property [_writable_, **signer**] payer
 * @category Instructions
 * @category CreateBlockDefinitionEnum
 * @category generated
 */
export type CreateBlockDefinitionEnumInstructionAccounts = {
  assembler: web3.PublicKey
  block: web3.PublicKey
  blockDefinition: web3.PublicKey
  blockDefinitionMint: web3.PublicKey
  authority: web3.PublicKey
  payer: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createBlockDefinitionEnumInstructionDiscriminator = [
  241, 173, 227, 189, 53, 230, 149, 206,
]

/**
 * Creates a _CreateBlockDefinitionEnum_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateBlockDefinitionEnum
 * @category generated
 */
export function createCreateBlockDefinitionEnumInstruction(
  accounts: CreateBlockDefinitionEnumInstructionAccounts,
  args: CreateBlockDefinitionEnumInstructionArgs,
  programId = new web3.PublicKey('AXX2agYcoDwGFsgEWvSitqfGH4ooKXUqK5P7Ch9raDJT')
) {
  const [data] = createBlockDefinitionEnumStruct.serialize({
    instructionDiscriminator: createBlockDefinitionEnumInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.assembler,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.block,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.blockDefinition,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.blockDefinitionMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.authority,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
